### ISSUE TITLE
Handling multiple environments

### ISSUE THREAD

**Issue by pdoreau** [GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild#2]
This tutorial is great ! It shows clearly how to make everything work with one environment, production.
What would be the extra steps to handle multiple environments ?

It would be interesting to add at least few lines for those interested to run one or more staging envs in a company for example.

What do you think ?

**Comment by MrTrustor** [comment]
Hi,

For this particular setup, the most straightforward way to add environments is to use different branches in the "env" repository.
However, because you probably have a few differences between environments (of configuration mainly, reflected in ConfigMaps and Secrets), this requires more than a simple "sed" as shown in the tutorial to generate the YAML. This where a tool like [kustomize](https://github.com/kubernetes-sigs/kustomize) becomes handy.

I'll add a note to the tutorial itself.
